name: Compile futurerestore
on: [push]
jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run compile script
        run: ./compile.sh

      - name: Zip files
        run: zip -r futurerestore_linux.zip bin/

      - name: Update latest release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: futurerestore_linux.zip
